version: '3.1'

networks:
  default:
    external: true
    name: ouroboros

services:
  db:
    container_name: mysql-financeportal-db
    image: mysql:8.3.0
    ports:
      - "3303:3306"
    environment:
      MYSQL_ROOT_PASSWORD: qwerty@123
      MYSQL_DATABASE: financePortal
    volumes:
      - mysql_financeportal_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]

  api:
    container_name: financeportal-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SERVER_PORT: 8085
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/financePortal
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: qwerty@123
    volumes:
      - financeportal_api:/app

volumes:
  mysql_financeportal_data:
    driver: local
  financeportal_api:
    driver: local