version: "3.1"

services:
  db:
    container_name: mysql-libraryportal-db
    image: mysql:8.3.0
    ports:
      - "3310:3306"
    expose:
      - "3306"
    deploy:
      mode: global
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE: ${DATABASE_NAME}
        MYSQL_USER: ${DATABASE_USER}
        MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - mysql_libraryportal_data:/var/lib/mysql

  api:
    container_name: libraryportal-api
    build:
      dockerfile: Dockerfile
    ports:
      - "8089:8089"
    depends_on:
      - db
    environment:
      SERVER_PORT: ${SERVER_PORT}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${DATABASE_USER}
      SPRING_DATASOURCE_PASSWORD: ${DATABASE_PASSWORD}
      SPRING_DATASOURCE_DRIVERCLASSNAME: ${DATABASE_DRIVER_CLASS_NAME}
      SPRING_JPA_HIBERNATE_DDL-AUTO: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
      JWT_SECRET: ${JWT_SECRET}
    volumes:
      - libraryportal_api:/app
    networks:
      - default

volumes:
  mysql_libraryportal_data:
    driver: local
  libraryportal_api:
    driver: local